// <auto-generated />
namespace Store.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class reset5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reset5));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111329390_reset5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
